version: "2.1"
services:
  code-server:
    image: lscr.io/linuxserver/code-server:4.13.0
    container_name: code-server
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Warsaw
      - PASSWORD=uMxy7+a48ag2T4ECj@9Xuz$^zG*q2TF?fM #optional
      - HASHED_PASSWORD= #optional
      - SUDO_PASSWORD=password #optional
      - SUDO_PASSWORD_HASH= #optional
      - PROXY_DOMAIN=codeshare.mpy.az #optional
      - DEFAULT_WORKSPACE=/config/workspace #optional
    volumes:
      - ./config:/config
    ports:
      - "8443:8443"
    restart: unless-stopped